USE DATABASE TELECOM_CHURN;
USE SCHEMA RAW;

-- look at IBM columns and sample data
SELECT * FROM IBM_TELCO LIMIT 10;

-- look at Maven columns and sample data
SELECT * FROM MAVEN_TELCO LIMIT 10;

-- look at Kaggle columns and sample data
SELECT * FROM KAGGLE_TELECOMS LIMIT 10;


-- IBM churn values
SELECT CHURN, COUNT(*) as cnt FROM IBM_TELCO GROUP BY CHURN;

-- Maven churn values (it has Customer Status, not just Churn)
SELECT CUSTOMER_STATUS, COUNT(*) as cnt FROM MAVEN_TELCO GROUP BY CUSTOMER_STATUS;

-- Kaggle churn values
SELECT CHURN, COUNT(*) as cnt FROM KAGGLE_TELECOMS GROUP BY CHURN;


SELECT CHURN_CATEGORY, COUNT(*) as cnt 
FROM MAVEN_TELCO 
WHERE CUSTOMER_STATUS = 'Churned'
GROUP BY CHURN_CATEGORY
ORDER BY cnt DESC;


USE DATABASE TELECOM_CHURN;
USE SCHEMA RAW;

-- check what columns IBM has
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'IBM_TELCO'
ORDER BY ORDINAL_POSITION;

SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'MAVEN_TELCO'
ORDER BY ORDINAL_POSITION;


SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'KAGGLE_TELECOMS'
ORDER BY ORDINAL_POSITION;

