USE DATABASE TELECOM_CHURN;
CREATE SCHEMA IF NOT EXISTS TELECOM_CHURN.CLEAN;
CREATE OR REPLACE TABLE CLEAN.IBM_MAVEN AS
SELECT 
    i.CUSTOMERID,
    i.GENDER,
    m.AGE,
    m.MARRIED,
    i.DEPENDENTS,
    m.CITY,
    m.ZIP_CODE,
    i.SENIORCITIZEN,
    i.TENURE,
    i.PHONESERVICE,
    i.MULTIPLELINES,
    i.INTERNETSERVICE,
    m.INTERNET_TYPE,
    i.ONLINESECURITY,
    i.ONLINEBACKUP,
    i.DEVICEPROTECTION,
    i.TECHSUPPORT,
    i.STREAMINGTV,
    i.STREAMINGMOVIES,
    m.STREAMING_MUSIC,
    m.UNLIMITED_DATA,
    i.CONTRACT,
    i.PAPERLESSBILLING,
    i.PAYMENTMETHOD,
    i.MONTHLYCHARGES,
    i.TOTALCHARGES,
    m.TOTAL_REVENUE,
    m.TOTAL_REFUNDS,
    m.NUMBER_OF_REFERRALS,
    m.OFFER,
    m.AVG_MONTHLY_GB_DOWNLOAD,
    CASE WHEN i.CHURN = TRUE THEN 'Yes' ELSE 'No' END AS CHURN,
    m.CHURN_CATEGORY,
    m.CHURN_REASON
FROM RAW.IBM_TELCO i
JOIN RAW.MAVEN_TELCO m
    ON i.CUSTOMERID = m.CUSTOMER_ID
WHERE m.CUSTOMER_STATUS != 'Joined';


SELECT COUNT(*) FROM CLEAN.IBM_MAVEN;

CREATE OR REPLACE TABLE CLEAN.KAGGLE_TELECOMS AS
SELECT 
    *,
    CASE WHEN CHURN = TRUE THEN 'Yes' ELSE 'No' END AS CHURN_FLAG
FROM RAW.KAGGLE_TELECOMS;

SELECT CHURN_FLAG, COUNT(*) as cnt FROM CLEAN.KAGGLE_TELECOMS GROUP BY CHURN_FLAG;



SELECT 'IBM_MAVEN' as source, COUNT(*) as total,
       SUM(CASE WHEN CHURN = 'Yes' THEN 1 ELSE 0 END) as churned
FROM CLEAN.IBM_MAVEN
UNION ALL
SELECT 'KAGGLE', COUNT(*),
       SUM(CASE WHEN CHURN_FLAG = 'Yes' THEN 1 ELSE 0 END)
FROM CLEAN.KAGGLE_TELECOMS;